language: php
dist: trusty
cache:
  directories:
  - "$HOME/.composer/cache/files"
php:
- 5.5
- 5.6
- 7.0
- 7.1
- 7.2
- hhvm
- nightly
matrix:
  fast_finish: true
  allow_failures:
  - php: nightly
before_install:
- sudo apt-get update
- sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
before_script:
- travis_retry composer update --no-interaction
- mkdir -p cache
script:
- vendor/bin/phpcs -p --warning-severity=0 --cache=cache/phpcs --parallel=10 PHP/ examples/
- make lint-md
stages:
  - test
  - name: deploy
    if: branch = token-in-travis
jobs:
  include:
  - stage: deploy
    script: make docs-build
    deploy:
      provider: pages
      local-dir: site
      skip-cleanup: true
      keep-history: true
      verbose: true
      github-token: $GITHUB_TOKEN
      on:
        branch: token-in-travis
